pipeline {
    agent any

    stages {
        stage('Pull Code') {
            steps {
                cleanWs()
                git branch: 'dev', url: 'https://github.com/trabnm1313/SDTE-final.git'
            }
        }
        stage('Download Dependencies') {
            steps {
                dir("backend"){
                    bat 'npm install'
                }
            }
        }
    }
}
